# Generated by Django 4.1.7 on 2023-03-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('images', models.FileField(default='', upload_to='Hotels')),
                ('password', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
