# Generated by Django 4.1.7 on 2023-03-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_user_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
