# Generated by Django 4.1.7 on 2023-03-31 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_hotel_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='location',
        ),
    ]
