# Generated by Django 4.1.7 on 2023-04-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_remove_hotel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='images1',
            field=models.FileField(default='', upload_to='Hotels'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='images2',
            field=models.FileField(default='', upload_to='Hotels'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='images3',
            field=models.FileField(default='', upload_to='Hotels'),
        ),
    ]
