# Generated by Django 4.1.7 on 2023-04-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0010_hotel_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
